name: hugo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out source
        uses: actions/checkout@v2
        
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest" # 可以修改为你使用的 Hugo 版本
          
      - name: Build
        run: hugo
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGE_ACTION_TOKEN }} # 另外还支持 github_token 和 personal_token
          external_repository: gyzboy/gyzboy.github.io` # 修改为你的 GitHub Pages 仓库
          publish_dir: ./public
          keep_files: false
          publish_branch: master
